//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIKit.h>

@class SCBehaviorSubject;

@interface SCCameraToolbarItemImpl : NSObject
{
    _Bool _isSelected;
    _Bool _shouldAlwaysBeHidden;
    _Bool _shouldIgnoreHidden;
    NSString *_accessibilityIdentifier;
    NSString *_accessibilityLabel;
    NSString *_accessibilityValueNormal;
    NSString *_accessibilityValueSelected;
    NSAttributedString *_attributedSelectedTitle;
    long long _cameraUIItem;
    SCBehaviorSubject *_canChangeSelectedEvent;
    SCBehaviorSubject *_canTapEvent;
    SCBehaviorSubject *_didCancelEvent;
    SCBehaviorSubject *_didChangeSelectedEvent;
    SCBehaviorSubject *_didChangeToolbarItemEvent;
    SCBehaviorSubject *_didTapEvent;
    NSString *_maskImageName;
    SCBehaviorSubject *_needsDisplayEvent;
    NSString *_normalImageName;
    NSString *_normalTitle;
    unsigned long long _position;
    NSString *_selectedImageName;
    NSString *_selectedTitle;
    SCBehaviorSubject *_willTapEvent;
}

@property(nonatomic) _Bool shouldIgnoreHidden; // @synthesize shouldIgnoreHidden=_shouldIgnoreHidden;
@property(nonatomic) _Bool shouldAlwaysBeHidden; // @synthesize shouldAlwaysBeHidden=_shouldAlwaysBeHidden;
@property(copy, nonatomic) NSString *selectedTitle; // @synthesize selectedTitle=_selectedTitle;
@property(copy, nonatomic) NSString *selectedImageName; // @synthesize selectedImageName=_selectedImageName;
@property(readonly, nonatomic) unsigned long long position; // @synthesize position=_position;
@property(copy, nonatomic) NSString *normalTitle; // @synthesize normalTitle=_normalTitle;
@property(copy, nonatomic) NSString *normalImageName; // @synthesize normalImageName=_normalImageName;
@property(copy, nonatomic) NSString *maskImageName; // @synthesize maskImageName=_maskImageName;
@property(nonatomic) _Bool isSelected; // @synthesize isSelected=_isSelected;
@property(nonatomic) long long cameraUIItem; // @synthesize cameraUIItem=_cameraUIItem;
@property(copy, nonatomic) NSAttributedString *attributedSelectedTitle; // @synthesize attributedSelectedTitle=_attributedSelectedTitle;
@property(copy, nonatomic) NSString *accessibilityValueSelected; // @synthesize accessibilityValueSelected=_accessibilityValueSelected;
@property(copy, nonatomic) NSString *accessibilityValueNormal; // @synthesize accessibilityValueNormal=_accessibilityValueNormal;
@property(copy, nonatomic) NSString *accessibilityLabel; // @synthesize accessibilityLabel=_accessibilityLabel;
@property(copy, nonatomic) NSString *accessibilityIdentifier; // @synthesize accessibilityIdentifier=_accessibilityIdentifier;
@property(readonly) long long actionType;
- (void)setNeedsDisplay:(_Bool)arg1;	// IMP=0x00000001056ec948
- (void)toggleSelection;	// IMP=0x00000001056ec8fc
@property(readonly, nonatomic) SCBehaviorSubject *didChangeToolbarItemEvent; // @synthesize didChangeToolbarItemEvent=_didChangeToolbarItemEvent;
@property(readonly, nonatomic) SCBehaviorSubject *canChangeSelectedEvent; // @synthesize canChangeSelectedEvent=_canChangeSelectedEvent;
@property(readonly, nonatomic) SCBehaviorSubject *needsDisplayEvent; // @synthesize needsDisplayEvent=_needsDisplayEvent;
@property(readonly, nonatomic) SCBehaviorSubject *didChangeSelectedEvent; // @synthesize didChangeSelectedEvent=_didChangeSelectedEvent;
@property(readonly, nonatomic) SCBehaviorSubject *didCancelEvent; // @synthesize didCancelEvent=_didCancelEvent;
@property(readonly, nonatomic) SCBehaviorSubject *didTapEvent; // @synthesize didTapEvent=_didTapEvent;
@property(readonly, nonatomic) SCBehaviorSubject *willTapEvent; // @synthesize willTapEvent=_willTapEvent;
@property(readonly, nonatomic) SCBehaviorSubject *canTapEvent; // @synthesize canTapEvent=_canTapEvent;
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001001d0dc0
- (id)initWithPosition:(unsigned long long)arg1;	// IMP=0x00000001001cfc50

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

